// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TOHPO.Data;

#nullable disable

namespace TOHPO.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129032606_opccional_correo_cliente")]
    partial class opccional_correo_cliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TOHPO.Models.Agente_Ventas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo_Electronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Proveedor")
                        .HasDatabaseName("IX_Agente_Ventas_Proveedor");

                    b.ToTable("Agente_Ventas");
                });

            modelBuilder.Entity("TOHPO.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("TOHPO.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo_Electronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primer_Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segundo_Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TOHPO.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Costo_Total_Grabado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Compra_Fecha");

                    b.HasIndex("Id_Proveedor")
                        .HasDatabaseName("IX_Compra_Proveedor");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("TOHPO.Models.Compra_Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Costo_Unitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_Compra")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto_Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto_Impuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Porcentaje_Descuento")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo_Producto");

                    b.HasIndex("Id_Compra");

                    b.ToTable("Compra_Detalle");
                });

            modelBuilder.Entity("TOHPO.Models.Compra_Metodo_Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Compra")
                        .HasColumnType("int");

                    b.Property<int>("Id_Metodo_Pago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Compra");

                    b.HasIndex("Id_Metodo_Pago");

                    b.ToTable("Compra_Metodo_Pago");
                });

            modelBuilder.Entity("TOHPO.Models.Detalle_Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad_Materia_Prima")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Inventario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Inventario");

                    b.ToTable("Detalle_Inventario");
                });

            modelBuilder.Entity("TOHPO.Models.Detalle_Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_Venta")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto_Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto_Impuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Porcentaje_Descuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo_Producto");

                    b.HasIndex("Id_Venta");

                    b.ToTable("Detalle_Venta");
                });

            modelBuilder.Entity("TOHPO.Models.Impuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Impuesto");
                });

            modelBuilder.Entity("TOHPO.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Compra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio_Venta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo_Producto")
                        .IsUnique()
                        .HasDatabaseName("IX_Inventario_Producto");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("TOHPO.Models.Materia_Prima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Unidad_Medida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materia_Prima");
                });

            modelBuilder.Entity("TOHPO.Models.Metodo_Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Metodo_Pago");
                });

            modelBuilder.Entity("TOHPO.Models.Motivo_Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motivo_Recordatorio");
                });

            modelBuilder.Entity("TOHPO.Models.Movimiento_Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Inventario")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Inventario");

                    b.ToTable("Movimiento_Inventario");
                });

            modelBuilder.Entity("TOHPO.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Abono")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Entrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Agente_Ventas")
                        .HasColumnType("int");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Agente_Ventas");

                    b.HasIndex("Id_Cliente");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("TOHPO.Models.Pedido_Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Unitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo_Producto");

                    b.HasIndex("Id_Pedido");

                    b.ToTable("Pedido_Detalle");
                });

            modelBuilder.Entity("TOHPO.Models.Presentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Unidad_Medida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Presentacion");
                });

            modelBuilder.Entity("TOHPO.Models.Produccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Planeada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Produccion_Fecha");

                    b.ToTable("Produccion");
                });

            modelBuilder.Entity("TOHPO.Models.Produccion_Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad_Producida")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("Cantidad_Programada")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("Codigo_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Produccion")
                        .HasColumnType("int");

                    b.Property<int>("Id_Receta")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo_Producto")
                        .HasDatabaseName("IX_Produccion_Detalle_Producto");

                    b.HasIndex("Id_Produccion");

                    b.HasIndex("Id_Receta")
                        .HasDatabaseName("IX_Produccion_Detalle_Receta");

                    b.ToTable("Produccion_Detalle");
                });

            modelBuilder.Entity("TOHPO.Models.Producto", b =>
                {
                    b.Property<string>("CodigoReferencia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Codigo_Barra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Es_De_Terceros")
                        .HasColumnType("bit");

                    b.Property<bool>("Es_Materia_Prima")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Id_Impuesto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Materia_Prima")
                        .HasColumnType("int");

                    b.Property<int>("Id_Presentacion")
                        .HasColumnType("int");

                    b.Property<int>("Tiempo_De_Vida")
                        .HasColumnType("int");

                    b.Property<int>("Unidad_Medida")
                        .HasColumnType("int");

                    b.HasKey("CodigoReferencia");

                    b.HasIndex("Id_Categoria");

                    b.HasIndex("Id_Impuesto")
                        .HasDatabaseName("IX_Producto_Impuesto");

                    b.HasIndex("Id_Materia_Prima");

                    b.HasIndex("Id_Presentacion");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("TOHPO.Models.Producto_Proveedor", b =>
                {
                    b.Property<string>("Codigo_Producto")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("Codigo_Producto", "Id_Proveedor");

                    b.HasIndex("Id_Proveedor");

                    b.ToTable("Producto_Proveedor");
                });

            modelBuilder.Entity("TOHPO.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo_Electronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("TOHPO.Models.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cantidad_Empaque")
                        .HasColumnType("float");

                    b.Property<string>("Codigo_Producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rendimiento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Codigo_Producto");

                    b.ToTable("Receta");
                });

            modelBuilder.Entity("TOHPO.Models.Receta_Materia_Prima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad_Requerida")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Materia_Prima")
                        .HasColumnType("int");

                    b.Property<int>("Id_Receta")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Unidad_Medida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Materia_Prima")
                        .HasDatabaseName("IX_Receta_Materia_Prima_Materia_Prima");

                    b.HasIndex("Id_Receta")
                        .HasDatabaseName("IX_Receta_Materia_Prima_Receta");

                    b.ToTable("Receta_Materia_Prima");
                });

            modelBuilder.Entity("TOHPO.Models.Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFinRecurrencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntervaloRecurrencia")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoRepeticiones")
                        .HasColumnType("int");

                    b.Property<int>("Motivo_RecordatorioId")
                        .HasColumnType("int");

                    b.Property<int?>("RecordatorioPadreId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoRecurrencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Motivo_RecordatorioId");

                    b.HasIndex("RecordatorioPadreId");

                    b.ToTable("Recordatorio");
                });

            modelBuilder.Entity("TOHPO.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Costo_Total_Gravado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Agente_Ventas")
                        .HasColumnType("int");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Venta_Fecha");

                    b.HasIndex("Id_Agente_Ventas")
                        .HasDatabaseName("IX_Venta_Agente_Ventas");

                    b.HasIndex("Id_Cliente")
                        .HasDatabaseName("IX_Venta_Cliente");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("TOHPO.Models.Venta_Metodo_Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Metodo_Pago")
                        .HasColumnType("int");

                    b.Property<int>("Id_Venta")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Metodo_Pago");

                    b.HasIndex("Id_Venta");

                    b.ToTable("Venta_Metodo_Pago");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TOHPO.Models.Agente_Ventas", b =>
                {
                    b.HasOne("TOHPO.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("TOHPO.Models.Compra", b =>
                {
                    b.HasOne("TOHPO.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("TOHPO.Models.Compra_Detalle", b =>
                {
                    b.HasOne("TOHPO.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Codigo_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Compra", "Compra")
                        .WithMany("Compra_Detalles")
                        .HasForeignKey("Id_Compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TOHPO.Models.Compra_Metodo_Pago", b =>
                {
                    b.HasOne("TOHPO.Models.Compra", "Compra")
                        .WithMany("Compra_Metodo_Pagos")
                        .HasForeignKey("Id_Compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Metodo_Pago", "Metodo_Pago")
                        .WithMany()
                        .HasForeignKey("Id_Metodo_Pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Metodo_Pago");
                });

            modelBuilder.Entity("TOHPO.Models.Detalle_Inventario", b =>
                {
                    b.HasOne("TOHPO.Models.Inventario", "Inventario")
                        .WithMany("Detalle_Inventarios")
                        .HasForeignKey("Id_Inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("TOHPO.Models.Detalle_Venta", b =>
                {
                    b.HasOne("TOHPO.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Codigo_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Venta", "Venta")
                        .WithMany("Detalle_Ventas")
                        .HasForeignKey("Id_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("TOHPO.Models.Inventario", b =>
                {
                    b.HasOne("TOHPO.Models.Producto", "Producto")
                        .WithOne("Inventario")
                        .HasForeignKey("TOHPO.Models.Inventario", "Codigo_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TOHPO.Models.Movimiento_Inventario", b =>
                {
                    b.HasOne("TOHPO.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("Id_Inventario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("TOHPO.Models.Pedido", b =>
                {
                    b.HasOne("TOHPO.Models.Agente_Ventas", "Agente_Ventas")
                        .WithMany()
                        .HasForeignKey("Id_Agente_Ventas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente_Ventas");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TOHPO.Models.Pedido_Detalle", b =>
                {
                    b.HasOne("TOHPO.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Codigo_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Pedido", "Pedido")
                        .WithMany("Pedido_Detalles")
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TOHPO.Models.Produccion_Detalle", b =>
                {
                    b.HasOne("TOHPO.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Codigo_Producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Produccion", "Produccion")
                        .WithMany("Produccion_Detalles")
                        .HasForeignKey("Id_Produccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("Id_Receta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produccion");

                    b.Navigation("Producto");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("TOHPO.Models.Producto", b =>
                {
                    b.HasOne("TOHPO.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("Id_Categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Impuesto", "Impuesto")
                        .WithMany("Productos")
                        .HasForeignKey("Id_Impuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Materia_Prima", "Materia_Prima")
                        .WithMany()
                        .HasForeignKey("Id_Materia_Prima")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Presentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("Id_Presentacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Impuesto");

                    b.Navigation("Materia_Prima");

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("TOHPO.Models.Producto_Proveedor", b =>
                {
                    b.HasOne("TOHPO.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Codigo_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("TOHPO.Models.Receta", b =>
                {
                    b.HasOne("TOHPO.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Codigo_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TOHPO.Models.Receta_Materia_Prima", b =>
                {
                    b.HasOne("TOHPO.Models.Materia_Prima", "Materia_Prima")
                        .WithMany()
                        .HasForeignKey("Id_Materia_Prima")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Receta", "Receta")
                        .WithMany("Receta_Materias_Primas")
                        .HasForeignKey("Id_Receta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia_Prima");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("TOHPO.Models.Recordatorio", b =>
                {
                    b.HasOne("TOHPO.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Motivo_Recordatorio", "Motivo_Recordatorio")
                        .WithMany()
                        .HasForeignKey("Motivo_RecordatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Recordatorio", "RecordatorioPadre")
                        .WithMany("RecordatoriosHijo")
                        .HasForeignKey("RecordatorioPadreId");

                    b.Navigation("Cliente");

                    b.Navigation("Motivo_Recordatorio");

                    b.Navigation("RecordatorioPadre");
                });

            modelBuilder.Entity("TOHPO.Models.Venta", b =>
                {
                    b.HasOne("TOHPO.Models.Agente_Ventas", "Agente_Ventas")
                        .WithMany()
                        .HasForeignKey("Id_Agente_Ventas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente_Ventas");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TOHPO.Models.Venta_Metodo_Pago", b =>
                {
                    b.HasOne("TOHPO.Models.Metodo_Pago", "Metodo_Pago")
                        .WithMany()
                        .HasForeignKey("Id_Metodo_Pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TOHPO.Models.Venta", "Venta")
                        .WithMany("Venta_Metodo_Pagos")
                        .HasForeignKey("Id_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metodo_Pago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("TOHPO.Models.Compra", b =>
                {
                    b.Navigation("Compra_Detalles");

                    b.Navigation("Compra_Metodo_Pagos");
                });

            modelBuilder.Entity("TOHPO.Models.Impuesto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TOHPO.Models.Inventario", b =>
                {
                    b.Navigation("Detalle_Inventarios");
                });

            modelBuilder.Entity("TOHPO.Models.Pedido", b =>
                {
                    b.Navigation("Pedido_Detalles");
                });

            modelBuilder.Entity("TOHPO.Models.Produccion", b =>
                {
                    b.Navigation("Produccion_Detalles");
                });

            modelBuilder.Entity("TOHPO.Models.Producto", b =>
                {
                    b.Navigation("Inventario")
                        .IsRequired();
                });

            modelBuilder.Entity("TOHPO.Models.Receta", b =>
                {
                    b.Navigation("Receta_Materias_Primas");
                });

            modelBuilder.Entity("TOHPO.Models.Recordatorio", b =>
                {
                    b.Navigation("RecordatoriosHijo");
                });

            modelBuilder.Entity("TOHPO.Models.Venta", b =>
                {
                    b.Navigation("Detalle_Ventas");

                    b.Navigation("Venta_Metodo_Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
